In [1]:
!nvidia-smi

Tue Dec 23 13:59:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


##  Introduction to Tensors

### Creating Tensors

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor as python int
scalar.item

<function Tensor.item>

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([
                        [[1,3,4],
                        [2,3,5],
                        [3,5,4]],
                        [[1,3,4],
                        [2,3,5],
                        [3,5,4]]
                        ])

TENSOR

tensor([[[1, 3, 4],
         [2, 3, 5],
         [3, 5, 4]],

        [[1, 3, 4],
         [2, 3, 5],
         [3, 5, 4]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 3, 4],
        [2, 3, 5],
        [3, 5, 4]])

### Random Tensors

Why random Tensors?

Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better understant the data.

'Start with random numbers' -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2793, 0.9058, 0.0665, 0.3169],
        [0.2690, 0.8088, 0.4850, 0.1631],
        [0.5509, 0.2913, 0.2710, 0.1801]])

In [19]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8846, 0.5397, 0.7170, 0.8169],
        [0.2043, 0.3519, 0.0254, 0.1144],
        [0.2667, 0.4129, 0.1217, 0.8792]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 2, 3, 4)
random_tensor

tensor([[[[0.9794, 0.2084, 0.0258, 0.4997],
          [0.5936, 0.7767, 0.6615, 0.3804],
          [0.4713, 0.2689, 0.7914, 0.5294]],

         [[0.6012, 0.9115, 0.3319, 0.8470],
          [0.3407, 0.1930, 0.5353, 0.3867],
          [0.5777, 0.6886, 0.6585, 0.6812]]],


        [[[0.8244, 0.2514, 0.5652, 0.5908],
          [0.2627, 0.7266, 0.0041, 0.3560],
          [0.3033, 0.4149, 0.6465, 0.7450]],

         [[0.4523, 0.8153, 0.4725, 0.3579],
          [0.6693, 0.1780, 0.6092, 0.2969],
          [0.5634, 0.8985, 0.4892, 0.1930]]],


        [[[0.9184, 0.0742, 0.4655, 0.9576],
          [0.8348, 0.1318, 0.0997, 0.8572],
          [0.7214, 0.5013, 0.3174, 0.8704]],

         [[0.4893, 0.6364, 0.8128, 0.2098],
          [0.0108, 0.6919, 0.5475, 0.5138],
          [0.7508, 0.6249, 0.7930, 0.4069]]]])

In [22]:
random_tensor.ndim

4

In [23]:
random_tensor.shape

torch.Size([3, 2, 3, 4])

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3) ) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
rand_test = torch.rand((256,256, 64, 64))
rand_test.ndim, rand_test.shape

(4, torch.Size([256, 256, 64, 64]))

 ### Zeros and Ones

In [26]:
random_tensor = torch.rand(3, 4)

In [27]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

  zeros are used for masking

In [29]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [31]:
zeros2 = torch.zeros(1, 7)
rand2 = torch.rand(3,7)

zeros2, rand2

(tensor([[0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0.6710, 0.4755, 0.9826, 0.7858, 0.5064, 0.4983, 0.1556],
         [0.0816, 0.0784, 0.3454, 0.1971, 0.9044, 0.8595, 0.9826],
         [0.4847, 0.4138, 0.1382, 0.6817, 0.1392, 0.3434, 0.0745]]))

In [32]:
f = zeros2 * rand2
f

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

# Creating a Range of tensors

In [33]:
# use torch.range()

torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
one_to_ten = torch.arange(step=10, start=1, end=100)

In [35]:
# Creating tensors like


ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & Deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [36]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor (e.g. float 32)
                               device=None, #
                               requires_grad=False # to track the gradients
                               )
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_16_tensor =  float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [40]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [41]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting Information from tensors (Tensor attributes)
1. Tensors not right datatype (tensor.dtype)
2. Tensors not right shape (tensor.shape)
3. Tensors not on the right device(tensor.device)

In [42]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4715, 0.3367, 0.3484, 0.4794],
        [0.4697, 0.6754, 0.6730, 0.0675],
        [0.6377, 0.6229, 0.6243, 0.3701]])

In [43]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

In [44]:
some_tensor.size()

torch.Size([3, 4])

In [45]:
 some_tensor = some_tensor.to(torch.device('cuda'))

In [46]:
some_tensor.device

device(type='cuda', index=0)

# Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [47]:
# Create a tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [48]:
tensor = tensor * 10

In [49]:
tensor

tensor([10, 20, 30])

In [50]:
tensor - 1

tensor([ 9, 19, 29])

In [51]:
# Try out Pytorch in-built functions

torch.mul(tensor, 30)

tensor([300, 600, 900])

## Matrix Multiplication

Two main ways of perofrming multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix Multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work

2. The resulting matrix has the shape of the ** outer dimensions**:
* `(2, 3) @ (3,2)` -> `(2,2)`
* `(3, 2) @ (2,3)` -> `(2, 2)`

In [52]:
# Element wise multiplication

print(f"{tensor} * {tensor}")
print(f"equals = {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
equals = tensor([100, 400, 900])


In [53]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(1400)

### One of the most common error in deep learning

In [54]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                      [8, 11],
                      [9, 12]])

In [55]:
torch.mm(tensor_A, tensor_B) # matmulll = mm

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**. A **transpose** switches the axes or dimensions of a given tensor.

In [57]:
tensor_B = tensor_B.T

In [58]:
torch.matmul(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor Aggregrations (min, max, sum, etc)

In [69]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [63]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [76]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [74]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [77]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))