In [ ]:
!nvidia-smi

Sat Oct 18 01:06:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


##  Introduction to Tensors

### Creating Tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor as python int
scalar.item

<function Tensor.item>

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([
                        [[1,3,4],
                        [2,3,5],
                        [3,5,4]],
                        [[1,3,4],
                        [2,3,5],
                        [3,5,4]]
                        ])

TENSOR

tensor([[[1, 3, 4],
         [2, 3, 5],
         [3, 5, 4],
         [3, 5, 4]],

        [[1, 3, 4],
         [2, 3, 5],
         [3, 5, 4],
         [3, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 4, 3])

In [ ]:
TENSOR[0]

tensor([[1, 3, 4],
        [2, 3, 5],
        [3, 5, 4],
        [3, 5, 4]])

### Random Tensors

Why random Tensors?

Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better understant the data.

'Start with random numbers' -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6575, 0.4687, 0.9813, 0.3845],
        [0.8340, 0.8539, 0.9380, 0.0084],
        [0.6514, 0.3943, 0.7956, 0.6718]])

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.1657, 0.8167, 0.5383, 0.9944],
         [0.4937, 0.6369, 0.4016, 0.3608],
         [0.0342, 0.7985, 0.9069, 0.2430]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([1, 3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3) ) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
rand_test = torch.rand((256,256, 64, 64))
rand_test.ndim, rand_test.shape

(4, torch.Size([256, 256, 64, 64]))

 ### Zeros and Ones

In [ ]:
random_tensor = torch.rand(3, 4)

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

  zeros are used for masking

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32